default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: food_product_development

test:
  <<: *default
  database: food_product_test

production:
  <<: *default
  database: food_product_production
  username: to_do
  password: <%= ENV['EXAMPLE_DATABASE_PASSWORD'] %>
